stages:
    - lint      # lint code
    - build     # make sure it builds
    - test      # unit tests, e2e test, security tests
    - security  # SAST, fuzzing (?)
    - deploy    # build and zip into artifacts

##### FREEZER JOBS #####

# This job will just lint the code, not blocking.
lint-freezer-job:
    stage: lint
    image: "python:3.10.3-slim-bullseye"
    allow_failure: true
    before_script:
        - pip install cpplint
    script:
        - "cpplint --recursive --linelength=120 --filter=-build/include_subdir,-readability/casting,-whitespace/braces,-whitespace/newline,-runtime/int,-readability/todo freezer"

build-freezer-job:
    stage: build
    image: registry.cri.epita.fr/kenji.gaillac/frozone/ubuntu/gcc
    variables:
        KERNEL_VERSION: 5.4.0-104-generic # used to compile lkm on that specific version
        IS_GITLAB_JOB: 1
    script:
        - meson build && meson compile -C build

test-freezer-job:
    stage: test
    image: registry.cri.epita.fr/kenji.gaillac/frozone/ubuntu/gcc
    script:
        - echo "Tests are only local, cannot run tests from the docker containers"
        - echo true

sast-semgrep-freezer-job:
    stage: security
    image: "python:3.10.3-slim-bullseye"
    before_script:
        - pip install semgrep colorama tabulate tabulate[widechars]
    script:
        - semgrep --metrics=off --config=security/freezer_module.yaml freezer
        - semgrep --metrics=off --config=security/freezer_module.yaml freezer -o res.json --json
        - python3 security/pretty_printer_semgrep.py res.json

##### CARTO JOBS #####

# This job will just lint the code, not blocking.
lint-carto-job:
    stage: lint
    image: "python:3.10.3-slim-bullseye"
    allow_failure: true
    before_script:
        - pip install cpplint
    script:
        - "cpplint --recursive --linelength=120 --filter=-build/include_subdir,-readability/casting,-whitespace/braces,-whitespace/comments,-whitespace/newline carto"

test-carto-job:
    stage: test
    image: registry.cri.epita.fr/kenji.gaillac/frozone/ubuntu/gcc
    variables:
        KERNEL_VERSION: 5.4.0-104-generic # used to compile lkm on that specific version
        IS_GITLAB_JOB: 1
    script:
        - meson build
        - meson compile -C build
        - meson test -v -C build 'CUnit - Public' 'CUnit - Carto - Private'

sast-semgrep-carto-job:
    stage: security
    image: "python:3.10.3-slim-bullseye"
    before_script:
        - pip install semgrep colorama tabulate tabulate[widechars]
    script:
        - semgrep --metrics=off --config=security/carto_module.yaml carto
        - semgrep --metrics=off --config=security/carto_module.yaml freezer -o res.json --json
        - python3 security/pretty_printer_semgrep.py res.json