stages:
    - lint # lint code
    - build # make sure it builds
    - test # unit tests, e2e test
    - deploy # build and zip into artifacts

##### FREEZER JOBS #####

# This job will just lint the code, not blocking.
lint-freezer-job:
    stage: lint
    image: "python:3.10.3-slim-bullseye"
    allow_failure: true
    before_script:
        - pip install cpplint
    script:
        - cpplint freezer/*.c freezer/*.h

# This job will run make on the freezer folder.
# BLOCKING if make fails
build-freezer-job:
    stage: build
    image: registry.cri.epita.fr/kenji.gaillac/frozone/ubuntu/gcc
    variables:
        KERNELDIR: /usr/lib/modules/5.4.0-104-generic/build # used to compile lkm on that specific version
        IS_GITLAB_JOB: 1
    script:
        - meson build && meson compile -C build

##### CARTO JOBS #####

# This job will just lint the code, not blocking.
lint-carto-job:
    stage: lint
    image: "python:3.10.3-slim-bullseye"
    allow_failure: true
    before_script:
        - pip install cpplint
    script:
        - "cpplint --recursive --linelength=120 --filter=-build/include_subdir,-readability/casting,-whitespace/braces carto"
