FROM ubuntu:21.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y build-essential linux-headers-5.11.0-49-generic python3 python3-pip \
    pkg-config libcunit1 libcunit1-doc libcunit1-dev \
    curl kmod

RUN pip3 install meson && pip3 install ninja